const ADDRESSING = {
    'IMPLIED':     'IMPLIED',
    'RELATIVE':    'RELATIVE',
    'IMMEDIATE':   'IMMEDIATE',
    'ACCUMULATOR': 'ACCUMULATOR',

    'ABSOLUTE':    'ABSOLUTE',
    'ABSOLUTE_X':  'ABSOLUTE_X',
    'ABSOLUTE_Y':  'ABSOLUTE_Y',

    'INDIRECT':    'INDIRECT',
    'INDIRECT_X':  'INDIRECT_X',
    'INDIRECT_Y':  'INDIRECT_Y',

    'ZERO_PAGE':   'ZERO_PAGE',
    'ZERO_PAGE_X': 'ZERO_PAGE_X',
    'ZERO_PAGE_Y': 'ZERO_PAGE_Y',
};

const MIRRORING = {
    'HORIZONTAL': 'HORIZONTAL',
    'VERTICAL': 'VERTICAL',
    'FOUR_SCREEN': 'FOUR_SCREEN'
};

const CONSTANTS = {
    'PRG_BANK_SIZE_IN_KB': 16,
    'CHR_BANK_SIZE_IN_KB': 8,
    'KB_IN_BYTES': 1024
};

export {ADDRESSING, MIRRORING, CONSTANTS};


